### ISSUE TITLE
Not compatible with the new sodium version

### ISSUE THREAD

**Issue by forditt** [jaredlll08/Ambient-Environment#36]
Does not work with Sodium 0.4.11

**Comment by jaredlll08** [comment]
More information please.

Mc version?
Mod loader version?
Ambient Environment version?

How is it not compatible, does it just not work, does it crash? etc

**Comment by forditt** [comment]
The mod just doesn't add visual changes:
![зображення](https://user-images.githubusercontent.com/105544922/236291991-51cc44c4-c58f-45ce-a672-5aa9d5de81da.png)

Minecraft - 1.19.4
Mod loader - fabric 0.14.17
Ambient Environment - 1.19.4-9.0.0.2

**Comment by jaredlll08** [comment]
From a quick look at their code, I don't know what they are doing to cause this, I know there is absolutely nothing *I* can do to fix this, if there was, sodium would be crashing instead of just my mod not doing anything (https://github.com/CaffeineMC/sodium-fabric/blob/1.19.3/dev/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/ColorResolverType.java#L15 would fail, leading to the thrown exception).

As it stands, I have extremely little interest in supporting sodium right now, so as long as the mods don't crash together, there is nothing that I going to be doing to resolve any issue.

**Comment by forditt** [comment]
I understand you, thanks for the answer
